openapi: 3.0.0
info:
  description: 'REST API endpoints for login-webpage'
  version: '0.0.0'
  title: 'login-webpage API endpoint'

servers:
  - url: http://localhost:5000/api
    description: dev server

components:
  securitySchemes:
    basic:
      type: http
      scheme: basic
    bearer:
      type: http
      scheme: bearer
  schemas:
    failedMessage:
      type: object
      properties:
        message:
          type: string


security:
  - basic: []

paths:
  /testlogin:
    get:
      operationId: testLoginGet
      summary: 'check if login works or not'
      security:
        - basic: []
      responses:
        '200':
          description: 'successful'
          content:
            application/json:
              schema:
                type: object
                properties:
                  valid:
                    type: boolean
                required:
                  - valid

  /login:
    post:
      operationId: loginPost
      summary: generates a session token
      security:
        - basic: []
      responses:
        '201':
          description: 'successful'
          content:
            application/json:
              schema:
                type: object
                properties:
                  session:
                    type: string
                  expiry:
                    type: string
                required:
                  - session
                  - expiry
        '401':
          description: 'failed'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/failedMessage'
  /userdata:
    get:
      operationId: userDataGet
      summary: retrieve basic user data
      security:
        - basic: []
        - bearer: []
      responses:
        '200':
          description: 'successful'
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                required:
                  - username
        '404':
          description: 'failure'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/failedMessage"

