openapi: 3.0.0
info:
  description: 'REST API endpoints for login-webpage'
  version: '0.0.0'
  title: 'login-webpage API endpoint'

servers:
  - url: http://localhost:5000/api
    description: dev server

components:
  securitySchemes:
    basic:
      type: http
      scheme: basic
    bearer:
      type: http
      scheme: bearer
  schemas:
    failedMessage:
      type: object
      properties:
        message:
          type: string
    task:
      type: object
      properties:
        created:
          type: string
        msg_id:
          type: integer
        starred:
          type: boolean
        text:
          type: string
        updated:
          type: string
        user_id:
          type: integer
      required:
        - msg_id
        - created
        - text
    tasks:
      type: array
      items:
        $ref: '#/components/schemas/task'

security:
  - basic: []

paths:
  /testlogin:
    get:
      operationId: testLoginGet
      summary: 'check if login works or not'
      security:
        - basic: []
      responses:
        '200':
          description: 'successful'
          content:
            application/json:
              schema:
                type: object
                properties:
                  valid:
                    type: boolean
                required:
                  - valid
  /user/{userid}/tasks:
    get:
      operationId: tasksGet
      summary: fetch all tasks for a user
      security:
        - basic: []
        - bearer: []
      parameters:
        - name: userid
          in: path
          description: User ID
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 'successful'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/tasks'
        '401':
          description: 'Unauthorized'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/failedMessage'
  /login:
    post:
      operationId: loginPost
      summary: generates a session token
      security:
        - basic: []
      responses:
        '201':
          description: 'successful'
          content:
            application/json:
              schema:
                type: object
                properties:
                  session:
                    type: string
                  expiry:
                    type: string
                required:
                  - session
                  - expiry
        '401':
          description: 'failed'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/failedMessage'
  /userdata:
    get:
      operationId: userDataGet
      summary: retrieve basic user data
      security:
        - basic: []
        - bearer: []
      responses:
        '200':
          description: 'successful'
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                  userid:
                    type: integer
                required:
                  - username
                  - userid
        '404':
          description: 'failure'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/failedMessage"
  /logout:
    delete:
      operationId: deleteSession
      summary: deletes curerent session
      security:
        - bearer: []
      responses:
        '204':
          description: 'session destroyed'
          content:
            application/json:
              schema: {}
        '404':
          description: 'token not found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/failedMessage'
        '500':
          description: 'cannot remove token for some reason'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/failedMessage'
